### ISSUE TITLE
What does umn do? 

### ISSUE THREAD

**Issue by BombSDiggity** [GTTFFXI/addons#17]

**Comment by BombSDiggity** [comment]
sorry wrong button. does this addon just pop unms? if so sounds perfect.

**Comment by danpelope** [comment]
Indeed it does.

One thing to note however. Because it just uses keypress sequences to pop
and is not doing so particularly intelligently, zones with more than 1 mob
will always pop the top one.

For example, in Boyahda it would repeat pop Ayapec and never make it to
Hidhaegg.

Happy hunting.

**Comment by BombSDiggity** [comment]
fantastic!! thank you!
