### ISSUE TITLE
AutoSkillchain suggestion

### ISSUE THREAD

**Issue by Gul3** [GTTFFXI/addons#8]
AutoSkillchain is awesome! A really really really good improvement would be to include a distance checker before launching. Probably seperate for ranged and melee as well. Too many times it fire off a ws at too long range, means blowing all tp and then really start the SC string on ws 2. Thank you for a great addtion though!

**Comment by danpelope** [comment]
Thanks for the suggestion. I'll look into it this weekend sometime.

**Comment by Gul3** [comment]
Yay, thanks for quick feedback!

My hunch is that if you modify this part:
if (player ~= nil) and (player.status == 1) and (mob ~= nil) then
                if player.vitals.tp > 999 then
                    handle_chain()
                    autowsLastCheck = now

into something like this:
if (player ~= nil) and (player.status == 1) and (mob ~= nil) and **(mob.distance < 5)** then
                if player.vitals.tp > 999 then
                    handle_chain()
                    autowsLastCheck = now

where my code ofc just is fictional right here, to illustrate. Guess you need something to register the actual distance, and seperate ranged/melee.

Thanks again!

**Comment by Gul3** [comment]
I actually have two more too. Both are nice to have, the previous one is a need to have - however if you have some time these would be really much appreciated as well:

1. Fallback ws. 
This would be a defined ws to continue spam after sc chain finished (unless target is dead). My workaround here was just add couple of of fudos into my 3 step. That works well, but a defined fallback would be cleaner. 

2. Verify if ws miss or connect
This is a really hot one but probably way more complicated. Understand if you dont want to bother. If the ws A miss retry ws A. If ws B miss still retry ws B, but check if it connect. If it connect do ws C, if it miss redo ws A or go to fallback ws. Makes sense?

**Comment by danpelope** [comment]
Tested it pretty extensively, give it a try and let me know.

**Comment by Gul3** [comment]
Hey! Yea this is great! It seems to work great for the initial hit. If it could be improved further, it should be checked for all ws, but I guess that is more complicated? I had some scenarios where whm pull off hate after first ws, so second ws in chain got lost. But it's miles better now!!! Great job man!

**Comment by danpelope** [comment]
It checks on every WS, but I played it really tight with the maximum distance so it might still occasionally fail. Maybe try adjusting the max melee distance down to 3.5ish might fix it. Line 28 if you want to try.

**Comment by Gul3** [comment]
Love your addon man. I have another suggestion/request. I don't think it's too big of a deal too hopefully. 
Mythic AM3 verify. F.x on SAM, it would be check if AM(3) is up, if not, use Tachi: Rana @3000 tp, then start SC loop. Makes sense? Would it be possible to do this? :D

**Comment by RudraXIV** [comment]
Hello, i just made Autoskillchain folder under addon etc, the addon is loaded well and all but when i fight a mob i cant self sc 
Ex: i made a light SC under WAR\Great Axe which is Upheaval then Ukko's Fury 
Upheaval land then when it should be Ukko's Fury turn i get this message : /ws Ukko's Fury <t> A commend error occured
It's also the same for all the other ws but Upheaval

**Comment by danpelope** [comment]
Can you send me a copy of the war\greataxe lua you made? I'll take a look
and see if anything looks out of place.

**Comment by danpelope** [comment]
also, out of curiosity, are you running AutoWS concurrently with
AutoSkillchain? they don't play well together.

**Comment by RudraXIV** [comment]
It's wrote like this :
return {
	{
		['name'] = 'light',
		['repeat'] = true,
		['ws'] = L{'Upheaval','Ukko\'s Fury'}
	},
}

**Comment by RudraXIV** [comment]
No i didnt use any of the Auto Mode from Selindrile gearswap.

**Comment by RudraXIV** [comment]
Ukko's Fury is wrote like this 'Ukko\'s Fury'

**Comment by danpelope** [comment]
I assume you mean with the backslash escape in front of the ' (e.g.
Ukko\\'s Fury). I'll try and look at it more when I get home tonight. Sorry
I couldn't solve it right away.

**Comment by danpelope** [comment]
Single backslash, not double. My mistake.

**Comment by RudraXIV** [comment]
Sure,  no problem Im not in a hurry ^^

**Comment by RudraXIV** [comment]
Ohh and i forgot to mention something.. when i load the addon i got two err message that says : 
Autoskillchain error : lor_ffxi and lor_resources not found. But the addon still load

**Comment by danpelope** [comment]
Ah, that's an easy one then. Check the readme on this page:
https://github.com/GTTFFXI/addons/tree/master/libs/lor.

For a quicker way to download the files all at once instead of one by one,
visit  https://kinolien.github.io/gitzip/ and paste the libs/lor url above
into the box and click Dowload.

**Comment by RudraXIV** [comment]
I've got all the libs but the weaponskill still doesnt work

**Comment by RudraXIV** [comment]
Also i cant open the tokens needed in the link :/
